# Generated by Django 4.2 on 2023-05-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KollabBusiness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('detail_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KollabTier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KollabCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=100)),
                ('currency_id', models.CharField(max_length=100)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.kollabbusiness')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.kollabcreator')),
            ],
        ),
        migrations.AddField(
            model_name='kollabbusiness',
            name='campaign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.kollabcampaign'),
        ),
        migrations.AddField(
            model_name='kollabbusiness',
            name='tier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.kollabtier'),
        ),
    ]
