# Generated by Django 4.2 on 2023-05-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KollabBusiness',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='business/logos')),
                ('cover', models.ImageField(upload_to='business/covers')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kollab Business',
                'verbose_name_plural': 'Kollab Businesses',
                'db_table': 'kollab_business',
            },
        ),
    ]
