# Generated by Django 4.2 on 2023-05-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KollabCreator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Kollab Creator',
                'verbose_name_plural': 'Kollab Creators',
                'db_table': 'kollab_creator',
            },
        ),
    ]
